name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Run the workflow when changes are pushed to the main branch

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use Python 3

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./docs/requirements.txt

    # Step 4: List installed packages (Optional)
    - name: List installed packages
      run: pip list

    # Step 5: Build the documentation
    - name: Build documentation
      run: |
        cd ./docs
        make html

    # Step 6: Confirm build files (Optional)
    - name: List build directory contents
      run: ls ./docs/build/html

    # Step 7: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html  # Path to the built documentation
